default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production_and_staging_default: &production_and_staging_default
  <<: *default
  adapter:
    auth_token_key: <%= ENV["ENCRYPTION_KEY"] %>
    auth_username_key: <%= ENV["ENCRYPTION_KEY"] %>
    auth_password_key: <%= ENV["ENCRYPTION_KEY"] %>

development_and_test: &development_and_test
  adapter:
    auth_token_key: 'token_key'
    auth_username_key: 'username_key'
    auth_password_key: 'password_key'

development:
  <<: *development_and_test
  <<: *default

test:
  <<: *development_and_test
  <<: *default

production:
  <<: *production_and_staging_default


staging:
  <<: *production_and_staging_default


