default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development_and_test: &development_and_test
  adapter:
    auth_token_key: 'token_key'
    auth_username_key: 'username_key'
    auth_password_key: 'password_key'

development:
  <<: *development_and_test
  <<: *default

test:
  <<: *development_and_test
  <<: *default

production:
  <<: *default


staging:
  <<: *default


