default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailer:
    domain: <%= ENV["MAILER_DOMAIN"] %>
    address: <%= ENV["MAILER_ADDRESS"] %>
    username: <%= ENV["MAILER_USERNAME"] %>
    password: <%= ENV["MAILER_PASSWORD"] %>
    host: <%= ENV["MAILER_HOST"] %>
    from: <%= ENV["MAILER_FROM"] %>
  trade_reporting_tool:
    host: <%= ENV["TRADE_REPORTING_HOST"] %>
    sign_in: <%= ENV["TRADE_REPORTING_SIGN_IN"] %>

production_and_staging: &production_and_staging
  <<: *default
  adapter:
    auth_token_key: <%= ENV["ENCRYPTION_KEY"] %>
    auth_username_key: <%= ENV["ENCRYPTION_KEY"] %>
    auth_password_key: <%= ENV["ENCRYPTION_KEY"] %>

development_and_test: &development_and_test
  adapter:
    auth_token_key: 'token_key'
    auth_username_key: 'username_key'
    auth_password_key: 'password_key'
  ga_tracking_id: UA-19524293-3

development:
  <<: *development_and_test
  <<: *default

test:
  <<: *development_and_test
  <<: *default

production:
  <<: *production_and_staging
  ga_tracking_id: UA-19524293-4

staging:
  <<: *production_and_staging
  ga_tracking_id: UA-19524293-3
